#ifndef _EXAMPLES_H
#define _EXAMPLES_H

#include "01-hello-world/main.h"
#include "02-element-buffer-object/main.h"
#include "03-draw-two-triangles/main.h"
#include "04-using-multiple-vao-and-vbo/main.h"
#include "05-using-multiple-shaders/main.h"
#include "06-pass-data-between-shaders/main.h"
#include "07-pass-data-using-vertex-attributes/main.h"
#include "08-pass-data-using-uniforms/main.h"
#include "09-using-texture/main.h"
#include "10-using-multiple-textures/main.h"
#include "11-transformation/main.h"
#include "12-coordinate-system/main.h"
#include "13-3d-cube/main.h"
#include "14-multiple-3d-cubes/main.h"
#include "15-camera-look-at-matrix/main.h"
#include "16-camera-control/main.h"
#include "17-light-scene/main.h"
#include "18-moving-light-source/main.h"
#include "19-material/main.h"
#include "20-different-materials/main.h"
#include "21-light-maps/main.h"
#include "22-directional-light/main.h"
#include "23-point-light/main.h"
#include "24-spot-light/main.h"
#include "25-loading-model-using-assimp/main.h"
#include "26-depth-test/main.h"
#include "27-stencil-test/main.h"
#include "28-discarding-fragment/main.h"
#include "29-blending/main.h"
#include "30-face-culling/main.h"
#include "31-frame-buffer/main.h"
#include "32-postprocessing/main.h"
#include "33-kernel-effects/main.h"
#include "context.h"

using namespace std;

#endif
